#!/bin/bash
: "${HTML_SUBDIR:?HTML_SUBDIR not set. Do not know where to go to get the built docs}"
: "${TARGET_DEV_SUBDIR:?TARGET_DEV_SUBDIR not set. Do not know where to go to get the built docs}"

message () {
  echo "
    message: $1
  "
}

CLONE_DIR="/tmp/docs"
message "CLONE_DIR=$CLONE_DIR"

message "removing CLONE_DIR=$CLONE_DIR (just in case it already exists)"
rm -rf $CLONE_DIR

git config --global user.email "Travis@nomail"
git config --global user.name "Travis"
git config --global push.default simple

message "cloning to $CLONE_DIR"
git clone git@github.com:NSLS-II/NSLS-II.github.io.git $CLONE_DIR

message "pushd-ing to CLONE_DIR=$CLONE_DIR"
pushd $CLONE_DIR

message "checking out --ophan temp_branch"
git checkout --orphan temp_branch

message "copying contents of $TRAVIS_BUILD_DIR/$HTML_SUBDIR to $CLONE_DIR/$TARGET_DEV_SUBDIR"
rsync -r $TRAVIS_BUILD_DIR/$HTML_SUBDIR/* $CLONE_DIR/$TARGET_DEV_SUBDIR

message "checking whether this is a tagged release"
if [ -n "$TRAVIS_TAG" ]; then
  message "this is a tagged release: copying dev/ to a tag directory"
  rsync -r $CLONE_DIR/$TARGET_DEV_SUBDIR $CLONE_DIR/$TARGET_DEV_SUBDIR/../$TRAVIS_TAG;
fi

message "Adding all changes to the git repo"
git add -A

message "Comitting the added files"
git commit -m "Autogenerated pages for $TRAVIS_REPO_SLUG from travis-ci `date`"

# Force push from the current repo's master branch to the remote
# repo's gh-pages branch. (All previous history on the master branch
# will be lost, since we are overwriting it.)
message "Pushing docs to NSLS-II.github.io"
git branch -D master
git branch -m master
git push --set-upstream origin master --force

message "Returning to previous directory"
popd
